### ISSUE TITLE
New Jython auto-completion pulldown filled wrongly

### ISSUE THREAD

**Issue by haesleinhuepf** [scijava/script-editor#53] opened 2021-01-25 21:20 UTC
Hi @acardona and @tferr ,

I just tested the new Jython auto-completion (on @tferr branch linked in #51 ) not sure if this branch is the issue, but when using  `IJ.getImage()` the auto-completion looks like this:

![image](https://user-images.githubusercontent.com/12660498/105767520-68368c00-5f5b-11eb-8ee9-53afb7d43c19.png)

Let me know if I can help tracing down this bug.

**Comment by tferr** [comment] 2021-01-25 21:56
@haesleinhuepf, you get this with script-editor 0.5.10-SNAPSHOT?

**Comment by tferr** [comment] 2021-01-25 22:14
@haesleinhuepf, I can reproduce it now after clearing up maven's cache. Please don't think I am ruthless. I promise you I did test things :). I must have broke something last minute. Oh boy, I hate working across repositories. It is painful. Do let me know if you have any tips..

**Comment by acardona** [comment] 2021-01-25 22:43
Don’t merge, rebase—that tends to do it for me.

Albert

**Comment by tferr** [comment] 2021-01-26 05:49
@haesleinhuepf ,
Thanks a lot for noticing the bug. Should be fixed now with https://github.com/fiji/jython-autocompletion/commit/9a83c9f20ed45e87155191dca7a4e545cab5cd6b. TLDR; While back (before @acardona's mechanism), we had implemented 'Fuzzy search' for the completion list. I remembered it only last minute and brought it back 'last minute'. Turns out, it needed some patching. It is working now. Please give it a go, and let me know if you notice something else.

To anyone new to this discussion, you will need to use script-editor 0.5.10-SNAPSHOT from https://github.com/tferr/Script_Editor/tree/autocompletion-vars and master from https://github.com/fiji/jython-autocompletion. I am attaching both artifacts below, in case it helps.

[artifacts.zip](https://github.com/scijava/script-editor/files/5871391/artifacts.zip)

Also, a reminder that I will need someone with write privileges to merge https://github.com/scijava/script-editor/pull/51 _AND_ release script-editor 0.5.10. Without it I won't be able to push the jython-autocompletion jar to the Java8 udpdate site.

**Comment by haesleinhuepf** [comment] 2021-01-26 15:18
Hey @tferr ,

I just downloaded the recent source of your script-editor branch and jhython-autocompletion but the bug appears still there:
![image](https://user-images.githubusercontent.com/12660498/105864185-fbba9c00-5ff1-11eb-9ffe-b0e1381a2b32.png)

I made sure that this commit is in:
![image](https://user-images.githubusercontent.com/12660498/105864266-0d03a880-5ff2-11eb-9f49-996bc55316f9.png)

Is there anythin else I need to update?

**Comment by imagejan** [comment] 2021-01-26 20:31
@tferr wrote:
> If you guys provide me write access, I can do it.

I can't take the responsibility of merging #51 (I didn't test myself yet), but I granted you write access to this repository, so you can take action yourself (hope that's alright, @ctrueden).

@tferr it would be nice if you also document your role in the `developers` section of `pom.xml`.

Thanks for your work!

**Comment by tferr** [comment] 2021-01-26 20:52
@haesleinhuepf, Bummer. I had tested the artifacts above on a virgin installation with no issues. Will look

**Comment by tferr** [comment] 2021-01-26 21:03
@haesleinhuepf, I understand now. It is all in the MCVE!! So my go-to testing snippet is:

```python
from ij import ImagePlus
imp = ImagePlus()
imp.
```
Only now I see that your report uses a static call from ij.IJ:
```python
from ij import IJ
imp = IJ.getImage()
imp.
```
So, good news: using the former I fixed a different bug yesterday :smile:  Bad news: You are right, the latter is still broken. 
Meanwhile, Can you please confirm that the ImagePlus() constructor completion works for you?I will look at the static completion tonight.
Thanks for the double bug report :wink:

**Comment by tferr** [comment] 2021-01-27 04:50
@haesleinhuepf, please push the latest changes from  https://github.com/fiji/jython-autocompletion. The issue with the static completions  is fixed.

![image](https://user-images.githubusercontent.com/2439948/105943650-aef5b600-602f-11eb-8373-f60dd21604bf.png)

Could you please test it further and check that everything works OK on your end?


> @tferr it would be nice if you also document your role in the `developers` section of `pom.xml`.

@imagejan, will do. FYI: the changes with #51 affect only two classes:

- [ClassUtil](https://github.com/scijava/script-editor/blob/cd732e25c828070b733d3144f6d119692316bb0f/src/main/java/org/scijava/ui/swing/script/autocompletion/ClassUtil.java): Added methods for generating completions with functional hyperlinks (Could be used in the future by other languages)
- [CompletionText](https://github.com/scijava/script-editor/blob/cd732e25c828070b733d3144f6d119692316bb0f/src/main/java/org/scijava/ui/swing/script/autocompletion/CompletionText.java): Convenience class to store data needed to generate a completion (replacement text, class name, summary, etc.)
I will _try_ to squash the multiple commits there into something more tractable.

**Comment by haesleinhuepf** [comment] 2021-01-27 13:50
Hey @tferr ,

both bugs are fixed, indeed! Thanks for investing your time! :-)

Just follow up bug report, do you know why the content of these two pulldowns (corresponding both examples discussed above) is different? It may not be an issue of the auto-completion. I'm just wondering: at least `imp.getProcessor()` should show up in both, or?
![image](https://user-images.githubusercontent.com/12660498/105999941-911b6600-60ae-11eb-8f87-def8690e0442.png)

![image](https://user-images.githubusercontent.com/12660498/106000337-00915580-60af-11eb-8334-928a5b258fbb.png)

Thanks again!

Cheers,
Robert

**Comment by haesleinhuepf** [comment] 2021-01-27 15:37
Is it possible that in the first case it only lists static methods?

**Comment by acardona** [comment] 2021-01-27 17:26
Indeed looks like the first case lists only static methods. That’s a bug. Means it’s using the regex shortcuts and not the full AST traversal to discover the type—a regression, I think.

**Comment by tferr** [comment] 2021-01-27 17:57
Bummer. Regression is likely. I don't recall noticing it when I took over. I will first look if the issue was already present in Albert's last commit and track it from there.

**Comment by tferr** [comment] 2021-01-27 21:57
@acardona: on the first case listing only static methods: The regression is already present before my commits. It is already present on your last change (https://github.com/fiji/jython-autocompletion/tree/4ed0695f41798fddfb03a3763e3c87358defdd66). Would be great if you (or @haesleinhuepf) could look into it.
Meanwhile, I could try to working on release the new script-editor.  That will make things easier  for everybody.

NB: I won't have much more time to work on this in the immediate future. If your time is also tight, I vote releasing things as they are (I am assuming that we have not broken anything for you @haesleinhuepf, correct?), and go through the improvements later on. Despite this issue, the current completion is quite functional, would be a pity to delay it further.

**Comment by tferr** [comment] 2022-03-01 06:08
Closing as this is now outdated and things have moved further  at https://github.com/scijava/script-editor-jython

**Closed by tferr** 2022-03-01 06:08 UTC

**Comment by acardona** [comment] 2022-03-01 15:06
Hi @tferr @haesleinhuepf: I can't reproduce the issue with static methods? See screenshot
![Screenshot from 2022-03-01 15-04-09](https://user-images.githubusercontent.com/50458/156193864-85645d88-0af2-4057-92bd-91b0be8cbb25.png)
